name: Bedwars
author: DelfikPro
softdepend: [LMAONetwork]
version: 3.0.0
main: pro.delfik.bedwars.BWPlugin
commands:
  bedwars:
    aliases: [bw]
  kill:
    aliases: [dupe, hack, fly, harakiri]
  setup:
    aliases: [setupslots]